#ifndef iMXRT1050_H
#define iMXRT1050_H
/* 
 * DMA Registers (p. 114)
 */
#define DMA_BASE               0x400E8000
#define DR_DMA_R               (*((volatile unsigned long *)(DMA_BASE + 0x000)))
#define ES_DMA_R               (*((volatile unsigned long *)(DMA_BASE + 0x004)))
#define ERQ_DMA_R              (*((volatile unsigned long *)(DMA_BASE + 0x00C)))
#define EEI_DMA_R              (*((volatile unsigned long *)(DMA_BASE + 0x014)))
#define CEEI_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x018)))
#define SEEI_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x019)))
#define CERQ_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x01A)))
#define SERQ_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x01B)))
#define CDNE_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x01C)))
#define SSRT_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x01D)))
#define CERR_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x01E)))
#define CINT_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x01F)))
#define INT_DMA_R              (*((volatile unsigned long *)(DMA_BASE + 0x024)))
#define ERR_DMA_R              (*((volatile unsigned long *)(DMA_BASE + 0x02C)))
#define HRS_DMA_R              (*((volatile unsigned long *)(DMA_BASE + 0x034)))
#define EARS_DMA_R             (*((volatile unsigned long *)(DMA_BASE + 0x044)))
#define DCHPRI3_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x100)))
#define DCHPRI2_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x101)))
#define DCHPRI1_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x102)))
#define DCHPRI0_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x103)))
#define DCHPRI7_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x104)))
#define DCHPRI6_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x105)))
#define DCHPRI5_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x106)))
#define DCHPRI4_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x107)))
#define DCHPRI11_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x108)))
#define DCHPRI10_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x109)))
#define DCHPRI9_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x10A)))
#define DCHPRI8_DMA_R          (*((volatile unsigned long *)(DMA_BASE + 0x10B)))
#define DCHPRI15_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x10C)))
#define DCHPRI14_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x10D)))
#define DCHPRI13_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x10E)))
#define DCHPRI12_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x10F)))
#define DCHPRI19_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x110)))
#define DCHPRI18_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x111)))
#define DCHPRI17_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x112)))
#define DCHPRI16_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x113)))
#define DCHPRI23_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x114)))
#define DCHPRI22_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x115)))
#define DCHPRI21_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x116)))
#define DCHPRI20_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x117)))
#define DCHPRI27_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x118)))
#define DCHPRI26_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x119)))
#define DCHPRI25_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x11A)))
#define DCHPRI24_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x11B)))
#define DCHPRI31_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x11C)))
#define DCHPRI30_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x11D)))
#define DCHPRI29_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x11E)))
#define DCHPRI28_DMA_R         (*((volatile unsigned long *)(DMA_BASE + 0x11F)))

//#define TCD0_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x1000)))
//#define TCD1_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x1000)))
//#define TCD2_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x1000)))
//#define TCD3_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))
//#define TCD4_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))
//#define TCD5_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))
//#define TCD6_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))
//#define TCD7_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))
//#define TCD8_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))
//#define TCD9_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))
//#define TCD10_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))
//#define TCD11_SADDR_DMA_R       (*((volatile unsigned long *)(DMA_BASE + 0x11F)))



/*
 * GPIO Registers (p. 932)
 */
// GPIOn base address: 401B_8000h + (n-1)×4000h, where n is from 1 to 4.
#define GPIO1_BASE             0x401B8000
#define DR_GPIO1_R             (*((volatile unsigned long *)(GPIO1_BASE + 0x000)))
#define GDIR_GPIO1_R           (*((volatile unsigned long *)(GPIO1_BASE + 0x004)))
#define DR_GPIO1_R             (*((volatile unsigned long *)(GPIO1_BASE + 0x008)))
#define ICR1_GPIO1_R           (*((volatile unsigned long *)(GPIO1_BASE + 0x00C)))
#define ICR2_GPIO1_R           (*((volatile unsigned long *)(GPIO1_BASE + 0x010)))
#define IMR_GPIO1_R            (*((volatile unsigned long *)(GPIO1_BASE + 0x014)))
#define ISR_GPIO1_R            (*((volatile unsigned long *)(GPIO1_BASE + 0x018)))
#define EDGE_SEL_GPIO1_R       (*((volatile unsigned long *)(GPIO1_BASE + 0x01C)))
#define DR_SET_GPIO1_R         (*((volatile unsigned long *)(GPIO1_BASE + 0x084)))
#define DR_CLEAR_GPIO1_R       (*((volatile unsigned long *)(GPIO1_BASE + 0x088)))
#define DR_TOGGLE_GPIO1_R      (*((volatile unsigned long *)(GPIO1_BASE + 0x08C)))

#define GPIO2_BASE             0x401BC000
#define DR_GPIO2_R             (*((volatile unsigned long *)(GPIO2_BASE + 0x000)))
#define GDIR_GPIO2_R           (*((volatile unsigned long *)(GPIO2_BASE + 0x004)))
#define DR_GPIO2_R             (*((volatile unsigned long *)(GPIO2_BASE + 0x008)))
#define ICR1_GPIO2_R           (*((volatile unsigned long *)(GPIO2_BASE + 0x00C)))
#define ICR2_GPIO2_R           (*((volatile unsigned long *)(GPIO2_BASE + 0x010)))
#define IMR_GPIO2_R            (*((volatile unsigned long *)(GPIO2_BASE + 0x014)))
#define ISR_GPIO2_R            (*((volatile unsigned long *)(GPIO2_BASE + 0x018)))
#define EDGE_SEL_GPIO2_R       (*((volatile unsigned long *)(GPIO2_BASE + 0x01C)))
#define DR_SET_GPIO2_R         (*((volatile unsigned long *)(GPIO2_BASE + 0x084)))
#define DR_CLEAR_GPIO2_R       (*((volatile unsigned long *)(GPIO2_BASE + 0x088)))
#define DR_TOGGLE_GPIO2_R      (*((volatile unsigned long *)(GPIO2_BASE + 0x08C)))

#define GPIO3_BASE             0x401C0000
#define DR_GPIO3_R             (*((volatile unsigned long *)(GPIO3_BASE + 0x000)))
#define GDIR_GPIO3_R           (*((volatile unsigned long *)(GPIO3_BASE + 0x004)))
#define DR_GPIO3_R             (*((volatile unsigned long *)(GPIO3_BASE + 0x008)))
#define ICR1_GPIO3_R           (*((volatile unsigned long *)(GPIO3_BASE + 0x00C)))
#define ICR2_GPIO3_R           (*((volatile unsigned long *)(GPIO3_BASE + 0x010)))
#define IMR_GPIO3_R            (*((volatile unsigned long *)(GPIO3_BASE + 0x014)))
#define ISR_GPIO3_R            (*((volatile unsigned long *)(GPIO3_BASE + 0x018)))
#define EDGE_SEL_GPIO3_R       (*((volatile unsigned long *)(GPIO3_BASE + 0x01C)))
#define DR_SET_GPIO3_R         (*((volatile unsigned long *)(GPIO3_BASE + 0x084)))
#define DR_CLEAR_GPIO3_R       (*((volatile unsigned long *)(GPIO3_BASE + 0x088)))
#define DR_TOGGLE_GPIO3_R      (*((volatile unsigned long *)(GPIO3_BASE + 0x08C)))

#define GPIO4_BASE             0x401C4000
#define DR_GPIO4_R             (*((volatile unsigned long *)(GPIO4_BASE + 0x000)))
#define GDIR_GPIO4_R           (*((volatile unsigned long *)(GPIO4_BASE + 0x004)))
#define DR_GPIO4_R             (*((volatile unsigned long *)(GPIO4_BASE + 0x008)))
#define ICR1_GPIO4_R           (*((volatile unsigned long *)(GPIO4_BASE + 0x00C)))
#define ICR2_GPIO4_R           (*((volatile unsigned long *)(GPIO4_BASE + 0x010)))
#define IMR_GPIO4_R            (*((volatile unsigned long *)(GPIO4_BASE + 0x014)))
#define ISR_GPIO4_R            (*((volatile unsigned long *)(GPIO4_BASE + 0x018)))
#define EDGE_SEL_GPIO4_R       (*((volatile unsigned long *)(GPIO4_BASE + 0x01C)))
#define DR_SET_GPIO4_R         (*((volatile unsigned long *)(GPIO4_BASE + 0x084)))
#define DR_CLEAR_GPIO4_R       (*((volatile unsigned long *)(GPIO4_BASE + 0x088)))
#define DR_TOGGLE_GPIO4_R      (*((volatile unsigned long *)(GPIO4_BASE + 0x08C)))

#define GPIO5_BASE             0x400C0000
#define DR_GPIO5_R             (*((volatile unsigned long *)(GPIO5_BASE + 0x000)))
#define GDIR_GPIO5_R           (*((volatile unsigned long *)(GPIO5_BASE + 0x004)))
#define DR_GPIO5_R             (*((volatile unsigned long *)(GPIO5_BASE + 0x008)))
#define ICR1_GPIO5_R           (*((volatile unsigned long *)(GPIO5_BASE + 0x00C)))
#define ICR2_GPIO5_R           (*((volatile unsigned long *)(GPIO5_BASE + 0x010)))
#define IMR_GPIO5_R            (*((volatile unsigned long *)(GPIO5_BASE + 0x014)))
#define ISR_GPIO5_R            (*((volatile unsigned long *)(GPIO5_BASE + 0x018)))
#define EDGE_SEL_GPIO5_R       (*((volatile unsigned long *)(GPIO5_BASE + 0x01C)))
#define DR_SET_GPIO5_R         (*((volatile unsigned long *)(GPIO5_BASE + 0x084)))
#define DR_CLEAR_GPIO5_R       (*((volatile unsigned long *)(GPIO5_BASE + 0x088)))
#define DR_TOGGLE_GPIO5_R      (*((volatile unsigned long *)(GPIO5_BASE + 0x08C)))


/*
 * I2C Registers
 */
#define LPI2C1_BASE             0x403F0000
#define VERID_LPI2C1_R          (*((volatile unsigned long *)(LPI2C1_BASE + 0x000)))
#define PARAM_LPI2C1_R          (*((volatile unsigned long *)(LPI2C1_BASE + 0x004)))
#define MCR_LPI2C1_R            (*((volatile unsigned long *)(LPI2C1_BASE + 0x010)))
#define MSR_LPI2C1_R            (*((volatile unsigned long *)(LPI2C1_BASE + 0x014)))  // p. 2599
#define MIER_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x018)))
#define MDER_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x01C)))
#define MCFGR0_LPI2C1_R         (*((volatile unsigned long *)(LPI2C1_BASE + 0x020)))
#define MCFGR1_LPI2C1_R         (*((volatile unsigned long *)(LPI2C1_BASE + 0x024)))
#define MCFGR2_LPI2C1_R         (*((volatile unsigned long *)(LPI2C1_BASE + 0x028)))
#define MCFGR3_LPI2C1_R         (*((volatile unsigned long *)(LPI2C1_BASE + 0x02C)))
#define MDMR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x040)))
#define MCCR0_LPI2C1_R          (*((volatile unsigned long *)(LPI2C1_BASE + 0x048)))
#define MCCR1_LPI2C1_R          (*((volatile unsigned long *)(LPI2C1_BASE + 0x050)))
#define MFCR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x058)))
#define MFSR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x05C)))
#define MTDR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x060)))
#define MRDR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x070)))
#define SCR_LPI2C1_R            (*((volatile unsigned long *)(LPI2C1_BASE + 0x110)))
#define SSR_LPI2C1_R            (*((volatile unsigned long *)(LPI2C1_BASE + 0x114)))
#define SIER_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x118)))
#define SDER_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x11C)))
#define SCFGR1_LPI2C1_R         (*((volatile unsigned long *)(LPI2C1_BASE + 0x124)))
#define SCFGR2_LPI2C1_R         (*((volatile unsigned long *)(LPI2C1_BASE + 0x128)))
#define SAMR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x140)))
#define SASR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x150)))
#define STAR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x154)))
#define STDR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x160)))
#define SRDR_LPI2C1_R           (*((volatile unsigned long *)(LPI2C1_BASE + 0x170)))

#define LPI2C2_BASE             0x403F4000
#define VERID_LPI2C2_R          (*((volatile unsigned long *)(LPI2C2_BASE + 0x000)))
#define PARAM_LPI2C2_R          (*((volatile unsigned long *)(LPI2C2_BASE + 0x004)))
#define MCR_LPI2C2_R            (*((volatile unsigned long *)(LPI2C2_BASE + 0x010)))
#define MSR_LPI2C2_R            (*((volatile unsigned long *)(LPI2C2_BASE + 0x014)))
#define MIER_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x018)))
#define MDER_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x01C)))
#define MCFGR0_LPI2C2_R         (*((volatile unsigned long *)(LPI2C2_BASE + 0x020)))
#define MCFGR1_LPI2C2_R         (*((volatile unsigned long *)(LPI2C2_BASE + 0x024)))
#define MCFGR2_LPI2C2_R         (*((volatile unsigned long *)(LPI2C2_BASE + 0x028)))
#define MCFGR3_LPI2C2_R         (*((volatile unsigned long *)(LPI2C2_BASE + 0x02C)))
#define MDMR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x040)))
#define MCCR0_LPI2C2_R          (*((volatile unsigned long *)(LPI2C2_BASE + 0x048)))
#define MCCR1_LPI2C2_R          (*((volatile unsigned long *)(LPI2C2_BASE + 0x050)))
#define MFCR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x058)))
#define MFSR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x05C)))
#define MTDR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x060)))
#define MRDR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x070)))
#define SCR_LPI2C2_R            (*((volatile unsigned long *)(LPI2C2_BASE + 0x110)))
#define SSR_LPI2C2_R            (*((volatile unsigned long *)(LPI2C2_BASE + 0x114)))
#define SIER_LPI2C_R            (*((volatile unsigned long *)(LPI2C2_BASE + 0x118)))
#define SDER_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x11C)))
#define SCFGR1_LPI2C2_R         (*((volatile unsigned long *)(LPI2C2_BASE + 0x124)))
#define SCFGR2_LPI2C2_R         (*((volatile unsigned long *)(LPI2C2_BASE + 0x128)))
#define SAMR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x140)))
#define SASR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x150)))
#define STAR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x154)))
#define STDR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x160)))
#define SRDR_LPI2C2_R           (*((volatile unsigned long *)(LPI2C2_BASE + 0x170)))

#define LPI2C3_BASE             0x403F8000
#define VERID_LPI2C3_R          (*((volatile unsigned long *)(LPI2C3_BASE + 0x000)))
#define PARAM_LPI2C3_R          (*((volatile unsigned long *)(LPI2C3_BASE + 0x004)))
#define MCR_LPI2C3_R            (*((volatile unsigned long *)(LPI2C3_BASE + 0x010)))
#define MSR_LPI2C3_R            (*((volatile unsigned long *)(LPI2C3_BASE + 0x014)))
#define MIER_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x018)))
#define MDER_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x01C)))
#define MCFGR0_LPI2C3_R         (*((volatile unsigned long *)(LPI2C3_BASE + 0x020)))
#define MCFGR1_LPI2C3_R         (*((volatile unsigned long *)(LPI2C3_BASE + 0x024)))
#define MCFGR2_LPI2C3_R         (*((volatile unsigned long *)(LPI2C3_BASE + 0x028)))
#define MCFGR3_LPI2C3_R         (*((volatile unsigned long *)(LPI2C3_BASE + 0x02C)))
#define MDMR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x040)))
#define MCCR0_LPI2C3_R          (*((volatile unsigned long *)(LPI2C3_BASE + 0x048)))
#define MCCR1_LPI2C3_R          (*((volatile unsigned long *)(LPI2C3_BASE + 0x050)))
#define MFCR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x058)))
#define MFSR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x05C)))
#define MTDR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x060)))
#define MRDR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x070)))
#define SCR_LPI2C3_R            (*((volatile unsigned long *)(LPI2C3_BASE + 0x110)))
#define SSR_LPI2C3_R            (*((volatile unsigned long *)(LPI2C3_BASE + 0x114)))
#define SIER_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x118)))
#define SDER_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x11C)))
#define SCFGR1_LPI2C3_R         (*((volatile unsigned long *)(LPI2C3_BASE + 0x124)))
#define SCFGR2_LPI2C3_R         (*((volatile unsigned long *)(LPI2C3_BASE + 0x128)))
#define SAMR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x140)))
#define SASR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x150)))
#define STAR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x154)))
#define STDR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x160)))
#define SRDR_LPI2C3_R           (*((volatile unsigned long *)(LPI2C3_BASE + 0x170)))

#define LPI2C4_BASE             0x403FC000
#define VERID_LPI2C4_R          (*((volatile unsigned long *)(LPI2C4_BASE + 0x000)))
#define PARAM_LPI2C4_R          (*((volatile unsigned long *)(LPI2C4_BASE + 0x004)))
#define MCR_LPI2C4_R            (*((volatile unsigned long *)(LPI2C4_BASE + 0x010)))
#define MSR_LPI2C4_R            (*((volatile unsigned long *)(LPI2C4_BASE + 0x014)))
#define MIER_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x018)))
#define MDER_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x01C)))
#define MCFGR0_LPI2C4_R         (*((volatile unsigned long *)(LPI2C4_BASE + 0x020)))
#define MCFGR1_LPI2C4_R         (*((volatile unsigned long *)(LPI2C4_BASE + 0x024)))
#define MCFGR2_LPI2C4_R         (*((volatile unsigned long *)(LPI2C4_BASE + 0x028)))
#define MCFGR3_LPI2C4_R         (*((volatile unsigned long *)(LPI2C4_BASE + 0x02C)))
#define MDMR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x040)))
#define MCCR0_LPI2C4_R          (*((volatile unsigned long *)(LPI2C4_BASE + 0x048)))
#define MCCR1_LPI2C4_R          (*((volatile unsigned long *)(LPI2C4_BASE + 0x050)))
#define MFCR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x058)))
#define MFSR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x05C)))
#define MTDR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x060)))
#define MRDR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x070)))
#define SCR_LPI2C4_R            (*((volatile unsigned long *)(LPI2C4_BASE + 0x110)))
#define SSR_LPI2C4_R            (*((volatile unsigned long *)(LPI2C4_BASE + 0x114)))
#define SIER_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x118)))
#define SDER_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x11C)))
#define SCFGR1_LPI2C4_R         (*((volatile unsigned long *)(LPI2C4_BASE + 0x124)))
#define SCFGR2_LPI2C4_R         (*((volatile unsigned long *)(LPI2C4_BASE + 0x128)))
#define SAMR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x140)))
#define SASR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x150)))
#define STAR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x154)))
#define STDR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x160)))
#define SRDR_LPI2C4_R           (*((volatile unsigned long *)(LPI2C4_BASE + 0x170)))

/*
 * SPI Registers
 */
#define LPSPI1_BASE             0x40394000
#define VERID_LPSPI1_R          (*((volatile unsigned long *)(LPSPI1_BASE + 0x000)))
#define PARAM_LPSPI1_R          (*((volatile unsigned long *)(LPSPI1_BASE + 0x004)))
#define CR_LPSPI1_R             (*((volatile unsigned long *)(LPSPI1_BASE + 0x010)))
#define SR_LPSPI1_R             (*((volatile unsigned long *)(LPSPI1_BASE + 0x014)))
#define IER_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x018)))
#define DER_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x01C)))
#define CFGR0_LPSPI1_R          (*((volatile unsigned long *)(LPSPI1_BASE + 0x020)))
#define CFGR1_LPSPI1_R          (*((volatile unsigned long *)(LPSPI1_BASE + 0x024)))
#define DMR0_LPSPI1_R           (*((volatile unsigned long *)(LPSPI1_BASE + 0x030)))
#define DMR1_LPSPI1_R           (*((volatile unsigned long *)(LPSPI1_BASE + 0x034)))
#define CCR_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x040)))
#define FCR_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x058)))
#define FSR_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x05C)))
#define TCR_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x060)))
#define TDR_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x064)))
#define RSR_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x070)))
#define RDR_LPSPI1_R            (*((volatile unsigned long *)(LPSPI1_BASE + 0x074)))

#define LPSPI2_BASE             0x40398000
#define VERID_LPSPI2_R          (*((volatile unsigned long *)(LPSPI2_BASE + 0x000)))
#define PARAM_LPSPI2_R          (*((volatile unsigned long *)(LPSPI2_BASE + 0x004)))
#define CR_LPSPI2_R             (*((volatile unsigned long *)(LPSPI2_BASE + 0x010)))
#define SR_LPSPI2_R             (*((volatile unsigned long *)(LPSPI2_BASE + 0x014)))
#define IER_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x018)))
#define DER_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x01C)))
#define CFGR0_LPSPI2_R          (*((volatile unsigned long *)(LPSPI2_BASE + 0x020)))
#define CFGR1_LPSPI2_R          (*((volatile unsigned long *)(LPSPI2_BASE + 0x024)))
#define DMR0_LPSPI2_R           (*((volatile unsigned long *)(LPSPI2_BASE + 0x030)))
#define DMR1_LPSPI2_R           (*((volatile unsigned long *)(LPSPI2_BASE + 0x034)))
#define CCR_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x040)))
#define FCR_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x058)))
#define FSR_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x05C)))
#define TCR_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x060)))
#define TDR_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x064)))
#define RSR_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x070)))
#define RDR_LPSPI2_R            (*((volatile unsigned long *)(LPSPI2_BASE + 0x074)))

#define LPSPI3_BASE             0x4039C000
#define VERID_LPSPI3_R          (*((volatile unsigned long *)(LPSPI3_BASE + 0x000)))
#define PARAM_LPSPI3_R          (*((volatile unsigned long *)(LPSPI3_BASE + 0x004)))
#define CR_LPSPI3_R             (*((volatile unsigned long *)(LPSPI3_BASE + 0x010)))
#define SR_LPSPI3_R             (*((volatile unsigned long *)(LPSPI3_BASE + 0x014)))
#define IER_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x018)))
#define DER_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x01C)))
#define CFGR0_LPSPI3_R          (*((volatile unsigned long *)(LPSPI3_BASE + 0x020)))
#define CFGR1_LPSPI3_R          (*((volatile unsigned long *)(LPSPI3_BASE + 0x024)))
#define DMR0_LPSPI3_R           (*((volatile unsigned long *)(LPSPI3_BASE + 0x030)))
#define DMR1_LPSPI3_R           (*((volatile unsigned long *)(LPSPI3_BASE + 0x034)))
#define CCR_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x040)))
#define FCR_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x058)))
#define FSR_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x05C)))
#define TCR_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x060)))
#define TDR_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x064)))
#define RSR_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x070)))
#define RDR_LPSPI3_R            (*((volatile unsigned long *)(LPSPI3_BASE + 0x074)))

#define LPSPI4_BASE             0x403A0000
#define VERID_LPSPI4_R          (*((volatile unsigned long *)(LPSPI4_BASE + 0x000)))
#define PARAM_LPSPI4_R          (*((volatile unsigned long *)(LPSPI4_BASE + 0x004)))
#define CR_LPSPI4_R             (*((volatile unsigned long *)(LPSPI4_BASE + 0x010)))
#define SR_LPSPI4_R             (*((volatile unsigned long *)(LPSPI4_BASE + 0x014)))
#define IER_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x018)))
#define DER_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x01C)))
#define CFGR0_LPSPI4_R          (*((volatile unsigned long *)(LPSPI4_BASE + 0x020)))
#define CFGR1_LPSPI4_R          (*((volatile unsigned long *)(LPSPI4_BASE + 0x024)))
#define DMR0_LPSPI4_R           (*((volatile unsigned long *)(LPSPI4_BASE + 0x030)))
#define DMR1_LPSPI4_R           (*((volatile unsigned long *)(LPSPI4_BASE + 0x034)))
#define CCR_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x040)))
#define FCR_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x058)))
#define FSR_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x05C)))
#define TCR_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x060)))
#define TDR_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x064)))
#define RSR_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x070)))
#define RDR_LPSPI4_R            (*((volatile unsigned long *)(LPSPI4_BASE + 0x074)))

#endif